### PR TITLE
fixes on database schema for jobs and destinations

### PR DESCRIPTION
**Pull request by titopixelfusion**
The flow should be: Agent is created, Added configuration for that agent, New job is started for a certain configuration, Job asks for a destination to store the artefact

Changes to reflect previous flow:
- removed agent_id from backup_jobs table
- added backup_jobs_id to backup_destinations table
- removed backup_destination_id from backup_configs

Also fixed tests

### CODE REVIEW

**Comment by jpcaparas** [comment]
Note/s to other PR reviewers:

- Do not forget to run `php artisan migrate` as there have been schema changes.

**Comment by jpcaparas** [comment]
@titopixelfusion

I have some questions regarding this after doing some testing on Swagger:

1. Shouldn't we have `/backups/destinations/` route that lists **ALL** back up destinations.
1. I'm not getting `/backups/destinations/{backupJobId}?page={page}`. Shouldn't it instead be `/backups/destinations/?job_id={jobId}&page={page} with both `jobId` and `page` being optional parameters **INSTEAD** of jobId being part of the URI segment. I'm not if the current route is compliant with REST standards.

**Comment by titopixelfusion** [comment]
@mauroveron reading your detailed explanation still gives me the impression that the suggested schema change makes sense. To me it is more intuitive to have destinations associates with jobs and not with configurations. 1 agent -> N configurations; 1 configuration -> N jobs; 1 job -> N destinations; The reason why a job might need N destinations is cos the upload might fail. 
Like you mentioned: "A backup destination describes the place where backup artefacts on backup jobs are stored." It seems more natural to have the relation between destinations and jobs directly.
This way, we still have 1 configuration -> N destinations but through jobs, not directly. What do you reckon?

**Comment by titopixelfusion** [comment]
After a conversation with @mauroveron , we decided to drop this PR, initial database schema seems correct.

**Pull request closed without merging**
